### PR TITLE
Expand on docs around scroll simulation

### PR DESCRIPTION
**Pull request by kirkbyo**
Added more commend which explain the different parameters around scroll.

### CODE REVIEW

**Comment by kirkbyo** [comment]
@matthew-carroll for review (I can't seem to add reviewers in this repo)

**Comment by matthew-carroll** [comment]
@kirkbyo can you please add a PR description about what this is doing? Also, it looks like this should wait for the other PR to merge, which will change the location of all the code you're editing.

**Comment by kirkbyo** [comment]
@matthew-carroll I added a description and rebased against main.

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Pull request merged**
